Repository euphony-io/wave-cam, pull requests merged in 2022-09, with the labels that each got.

#2 [feature] boilerplate code 관리를 위한 common-lib 추가 #1
  build.gradle
  common-lib/.gitignore
  common-lib/build.gradle
  common-lib/consumer-rules.pro
  common-lib/proguard-rules.pro
  common-lib/src/androidTest/java/com/euphonyio/common_lib/ExampleInstrumentedTest.kt
  common-lib/src/main/AndroidManifest.xml
  common-lib/src/main/java/com/euphonyio/common_lib/Constants.kt
  common-lib/src/test/java/com/euphonyio/common_lib/ExampleUnitTest.kt
  eupi-camera/build.gradle
  eupi-camera/src/main/AndroidManifest.xml
  eupi-shutter/build.gradle
  settings.gradle
Labels: enhancement, feature

#6 [feature] eupi-shutter UI 구현
  eupi-shutter/src/main/java/com/euphonyio/eupi_shutter/Command.kt
  eupi-shutter/src/main/java/com/euphonyio/eupi_shutter/ShutterActivity.kt
  eupi-shutter/src/main/java/com/euphonyio/eupi_shutter/ui/viewmodel/ShutterViewModel.kt
Labels: enhancement, feature

#8 [settings] eupi-camera Gradle 및 Manifest 세팅
  common-lib/build.gradle
  eupi-camera/build.gradle
  eupi-camera/src/main/AndroidManifest.xml
  eupi-camera/src/main/java/com/euphonyio/eupi_camera/CameraApplication.kt
  eupi-camera/src/main/res/xml/file_paths.xml
Labels: setting

#11 [feature] eupi-camera EuPI 수신 구현
  build.gradle
  eupi-camera/src/main/java/com/euphonyio/eupi_camera/fragments/CameraFragment.kt
Labels: enhancement, feature

#13 [chore] 기존 PR에서 빠진 부분 추가
  build.gradle
  eupi-camera/build.gradle
  eupi-camera/src/main/java/com/euphonyio/eupi_camera/fragments/CameraFragment.kt
Labels: chore

#14 [feature] eupi-shutter 송신 로직 구현
  build.gradle
  eupi-shutter/build.gradle
  eupi-shutter/src/main/AndroidManifest.xml
  eupi-shutter/src/main/java/com/euphonyio/eupi_shutter/ShutterActivity.kt
  eupi-shutter/src/main/java/com/euphonyio/eupi_shutter/ui/screen/ShutterComposable.kt
  eupi-shutter/src/main/java/com/euphonyio/eupi_shutter/ui/viewmodel/ShutterViewModel.kt
Labels: feature
